name: movies_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  go_router: ^6.0.9
  google_fonts: ^4.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.12
  readmore: ^2.2.0
  shimmer: ^2.0.0
  stream_transform: ^2.1.0
  url_launcher: ^6.1.8
  envied: ^0.3.0+3
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.3.5

flutter_native_splash:
  android: true
  ios: true
  web: false

  image: "assets/images/icon.png"
  color: "#2A52BE"

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  envied_generator: ^0.3.0+3
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/icon.png
